### ISSUE TITLE
Cannot detect Oculus DK2 and fatal error "Segmentation fault: 11"

### ISSUE THREAD

**Issue by putrinolab1** [floored/node-oculus#2]
Hello! While trying to get node-oculus up and running with the supplied example script (pollSensorDK2.js) an error is thrown and the script quits. The terminal response is "FAILED (is the Oculus plugged in?)". After taking the code from the README and placing it into it's own file, the same error occurs which is now followed by the message "Segmentation fault: 11". 

Any advice as to where to go from here to get this up and running? The code is being run/compiled on OSX Mavericks. During compile time there are a handful of warnings but no [fatal] errors. 

Thanks!

**Comment by bleveque** [comment]
Hi @putrinolab1! Just to check, have you installed the oculus runtime, and is the oculus indeed plugged in? I'm guessing the segfault is coming from trying to call methods that depend on the oculus headset being discovered (note: the example script has a check to make sure the headset is found before calling any of these methods).

**Comment by putrinolab1** [comment]
@bleveque - Thanks for the swift response. After reinstalling the oculus runtime, everything worked as expected. Excellent package - thanks!

**Comment by bleveque** [comment]
@putrinolab1 glad to hear it!
